### ISSUE TITLE
During inheritance of ArrayAccess. Uncaught Return type (ObjectSerializer) PHP 8.1

### ISSUE THREAD

**Issue by osom-alexandr** [amazon-php/sp-api-sdk#230] opened 2022-08-15 16:31 UTC
Hi

I have a problem with ObjectSerializer on PHP Version 8.1.7

During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of AmazonPHP\SellingPartner\Model\ProductTypesDefinitions\ProductTypeList::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/ProductTypesDefinitions/ProductTypeList.php:219
Stack trace:

0 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/ProductTypesDefinitions/ProductTypeList.php(17): Gepard\Log\Components\ConsoleErrorHandler->handleError(code: '...', message: '...', file: '...', line: '...')

1 /var/www/html/vendor/composer/ClassLoader.php(571): ::unknown()

2 /var/www/html/vendor/composer/ClassLoader.php(428): ::Composer\Autoload\includeFile(file: '...')

3 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php(360): Composer\Autoload\ClassLoader->loadClass(class: '...')

4 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php(360): ::method_exists(object_or_class: '...', method: '...')

5 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Api/DefinitionsApi/ProductTypesDefinitionsSDK.php(396): AmazonPHP\SellingPartner\ObjectSerializer::deserialize(configuration: '...', data: '...', class: '...', httpHeaders: '...')
AmazonPHP\SellingPartner\Api\DefinitionsApi\ProductTypesDefinitionsSDK->searchDefinitionsProductTypes(accessToken: '...', region: '...', marketplace_ids: '...', keywords: '...')

6 {main} in /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/ProductTypesDefinitions/ProductTypeList.php on line 17

**Comment by norberttech** [comment] 2022-08-15 17:06
Hey, could you share some code that would help to reproduce this bug?

**Comment by osom-alexandr** [comment] 2022-08-16 07:59
@norberttech 

Example request:
```
 $response = $sdk
                ->productTypesDefinitions()
                ->searchDefinitionsProductTypes(
                   $accessToken,
                  'eu-west-1',
                   ['A1805IZSGTT6HS'],
                );
```

**Comment by norberttech** [comment] 2022-08-16 08:21
Thanks, this is not a bug, it's just a deprecation notice which will go away in version 5.x after I bum the minimum php required version from 7.4 into 8.1
Currently, because of 7.4 support, there is nothing we can do here, however, your system should not recognize deprecation warnings as exceptions, you might want to look into your error handler and tune it. 
I'm closing this since there are no action items here

**Closed as completed by norberttech** 2022-08-16 08:21 UTC

**Comment by Stevad** [comment] 2022-08-16 08:29
@norberttech Yes, this is a deprecation warning. And any project that uses your library with strict error reporting can fail with a similar error.

As far as I see in almost all libraries that we also use on our project where similar errors appear, maintainers add `#[\ReturnTypeWillChange]` attributes in order to solve possible code incompatibility.

Is it possible to add that attribute where such incompatibility might appear?

**Comment by norberttech** [comment] 2022-08-16 08:37
afaik it would break PHP 7.4 since attributes were introduced in PHP 8.0 which is much worse the deprecation warning at 8.0+. Release 5.x will drop support for PHP 7.4 entirely, I hope to work on it later this or next week.

**Comment by Stevad** [comment] 2022-08-16 08:40
@norberttech It will not break. Because `#` in the beginning was selected by PHP maintainers as a character that will be parsed as a "comment" in PHP < 8.0 or as an "attribute" in PHP >= 8.0 (if followed syntax `#[...something...]`.

So for PHP 7.4, this will be a comment without any additional logic.

**Comment by Stevad** [comment] 2022-08-16 08:43
As proof, please, look to the official AWS SDK:
- https://github.com/aws/aws-sdk-php/blob/master/composer.json, it supports PHP >= 5.5
- https://github.com/aws/aws-sdk-php/blob/master/src/Api/AbstractModel.php - in this class they mark methods with attribute to avoid deprecation notices in PHP 8.0+

**Comment by norberttech** [comment] 2022-08-16 08:51
oh I see, in that case, feel free to open PR with proper adjustment, thanks for pointing this out!

**Comment by Stevad** [comment] 2022-08-16 09:03
I have opened a new issue instead of this. Will try to find time to open PR.
