### ISSUE TITLE
Listing API item deserialization error

### ISSUE THREAD

**Issue by Stevad** [amazon-php/sp-api-sdk#186] opened 2022-06-15 08:57 UTC
I am trying to load the product using Listing API SDK.

Request log:

```
[2022-06-15T08:49:19.965991+00:00] amazon.DEBUG: Amazon Selling Partner API pre request {"api":"ListingsItems","operation":"getListingsItem","request_correlation_id":"86975203-3ed0-485a-a895-4ddbf92df76c","request_body":"","request_headers":{"content-type":["applica
tion/json"],"accept":["application/json"],"host":["sellingpartnerapi-eu.amazon.com"],"user-agent":["Library amazon-php/sp-api-php (language=PHP 7.4.29; Platform=Linux 5.10.102.1-microsoft-standard-WSL2 x86_64)"],"x-amz-date":["20220615T084914Z"]},"request_uri":"https://se
llingpartnerapi-eu.amazon.com/listings/2021-08-01/items/ASUBR/90NB0SL1-M10530?marketplaceIds=A1RKKUPIHCS9HS&includedData=summaries%2Cattributes%2Cissues%2Coffers%2CfulfillmentAvailability%2Cprocurement"}
```

The request is successful, I see in logs that the response contains product data, but SDK fails on deserializing:

```
[2022-06-15T08:49:46.547226+00:00] app.CRITICAL: TypeError: Argument 1 passed to AmazonPHP\SellingPartner\Model\ListingsItems\Item::setAttributes() must be an object or null, array given, called in /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php on line 381 (/var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/ListingsItems/Item.php, line 308) {"trace":"
#0 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php(381): AmazonPHP\\SellingPartner\\Model\\ListingsItems\\Item->setAttributes()
#1 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Api/ListingsApi/ListingsItemsSDK.php(392): AmazonPHP\\SellingPartner\\ObjectSerializer::deserialize()

... below stack trace is on files that are not related to the library ...
```

If I remove `attributes` from `includedData` in the query - the issue disappears.

**Comment by norberttech** [comment] 2022-06-17 20:19
Could you check the latest version (not tagged yet) if the problem was solved? I changed few things https://github.com/amazon-php/sp-api-sdk/pull/188

**Comment by Stevad** [comment] 2022-06-20 14:14
@norberttech 

Checked on commit `d99f40f8438dcce4d1a4f28767032cb883e26603`

Still no luck. Error is the same.

```
[2022-06-20T14:12:24.347520+00:00] app.CRITICAL: TypeError: Argument 1 passed to AmazonPHP\SellingPartner\Model\ListingsItems\Item::setAttributes() must be an object or null, array given, called in /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php on line 382 (/var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Model/ListingsItems/Item.php, line 308) 

Trace:
#0 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/ObjectSerializer.php(382): AmazonPHP\\SellingPartner\\Model\\ListingsItems\\Item->setAttributes()
#1 /var/www/html/vendor/amazon-php/sp-api-sdk/src/AmazonPHP/SellingPartner/Api/ListingsApi/ListingsItemsSDK.php(384): AmazonPHP\\SellingPartner\\ObjectSerializer::deserialize()
...
```

**Comment by norberttech** [comment] 2022-06-20 14:20
Could you please provide me some sample code that would help me reproduce this issue locally?

**Comment by Stevad** [comment] 2022-06-20 14:27
@norberttech This is a live system that operates with client products on Amazon.

In short, the code is similar to this:

```php
try {
    $response = $sdk
        ->listingsItems()
        ->getListingsItem(
            $accessToken, // access token loaded without issues
            'eu-west-1',
            $vendorCode,  // this is the request for client that uses vendor central
            $sku,         // SKU of the product that really exists on Amazon 
            ['A13V1IB3VIYZZH'],
            null,
            ['summaries', 'attributes', 'issues', 'offers', 'fulfillmentAvailability', 'procurement']
        );
} catch (\AmazonPHP\SellingPartner\Exception\ApiException $e) {
    // here I got exception that you see
}
```

**Comment by Stevad** [comment] 2022-06-20 14:32
@norberttech Some further investigation. I got a response without exception only if I request with included data `['summaries']`. 

In all other cases - there will be different errors when one or another field is of incorrect or unexpected type, etc.

**Comment by norberttech** [comment] 2022-06-20 15:43
Thanks @Stevad that example is all I needed, the problem comes from the [model definition](https://github.com/amzn/selling-partner-api-models/blob/main/models/listings-items-api-model/listingsItems_2021-08-01.json#L1233-L1236). Amazon says that "attributes" are "object" type, the problem is that for PHP "object" means an object, not "json object" which in PHP is an associative array. 
This can be fixed by [rector](https://github.com/amazon-php/sp-api-sdk/blob/4.x/rector.php). I'm now regenerating entire SDK.

**Comment by norberttech** [comment] 2022-06-20 16:35
Could you please confirm that latest changes works for you? https://github.com/amazon-php/sp-api-sdk/pull/190 

Once you confirm all is good I will tag new relase

**Comment by Stevad** [comment] 2022-06-21 07:27
@norberttech It is working now, thank you. 

Waiting for stable tag release.

**Comment by norberttech** [comment] 2022-06-21 07:35
[4.0.5](https://github.com/amazon-php/sp-api-sdk/releases/tag/4.0.5)  🤝

**Closed as completed by norberttech** 2022-06-21 07:35 UTC
